name: quiz_app
description: Простая игра-викторина на Flutter
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.2.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6
  flutter_svg: ^2.0.10
  url_launcher: ^6.3.1
  shared_preferences: ^2.3.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0
  flutter_launcher_icons: ^0.14.3

flutter:
  uses-material-design: true

  assets:
    - assets/flags/
    - assets/question_images/
    - output/imagegen/world_map_no_labels_8k.png
    - assets/data/russia/en/
    - assets/data/russia/ru/
    - assets/data/russia/sah/
    - assets/data/russia/yakutia/
    - assets/data/russia/yakutia/en/
    - assets/data/russia/yakutia/ru/
    - assets/data/russia/yakutia/sah/
    - assets/data/russia/dagestan/
    - assets/data/russia/dagestan/en/
    - assets/data/russia/dagestan/ru/
    - assets/data/russia/dagestan/sah/
    - assets/data/usa/en/
    - assets/data/usa/ru/
    - assets/data/usa/sah/
    - assets/data/usa/oklahoma/en/
    - assets/data/usa/oklahoma/ru/
    - assets/data/usa/oklahoma/sah/
    - assets/data/usa/texas/en/
    - assets/data/usa/texas/ru/
    - assets/data/usa/texas/sah/
    - assets/data/china/en/
    - assets/data/china/ru/
    - assets/data/china/sah/
    - assets/data/vietnam/en/
    - assets/data/vietnam/ru/
    - assets/data/vietnam/sah/
    - assets/data/japan/en/
    - assets/data/japan/ru/
    - assets/data/japan/sah/
    - assets/data/mexico/en/
    - assets/data/mexico/ru/
    - assets/data/mexico/sah/
    - assets/data/canada/en/
    - assets/data/canada/ru/
    - assets/data/canada/sah/
    - assets/data/poland/en/
    - assets/data/poland/ru/
    - assets/data/poland/sah/
    - assets/data/france/en/
    - assets/data/france/ru/
    - assets/data/france/sah/
    - assets/data/czechia/en/
    - assets/data/czechia/ru/
    - assets/data/czechia/sah/
    - assets/data/slovakia/en/
    - assets/data/slovakia/ru/
    - assets/data/slovakia/sah/
    - assets/data/hungary/en/
    - assets/data/hungary/ru/
    - assets/data/hungary/sah/
    - assets/data/serbia/en/
    - assets/data/serbia/ru/
    - assets/data/serbia/sah/
    - assets/data/norway/en/
    - assets/data/norway/ru/
    - assets/data/norway/sah/
    - assets/data/sweden/en/
    - assets/data/sweden/ru/
    - assets/data/sweden/sah/
    - assets/data/finland/en/
    - assets/data/finland/ru/
    - assets/data/finland/sah/
    - assets/data/iceland/en/
    - assets/data/iceland/ru/
    - assets/data/iceland/sah/
    - assets/data/romania/en/
    - assets/data/romania/ru/
    - assets/data/romania/sah/
    - assets/data/bulgaria/en/
    - assets/data/bulgaria/ru/
    - assets/data/bulgaria/sah/
    - assets/data/greece/en/
    - assets/data/greece/ru/
    - assets/data/greece/sah/
    - assets/data/portugal/en/
    - assets/data/portugal/ru/
    - assets/data/portugal/sah/
    - assets/data/austria/en/
    - assets/data/austria/ru/
    - assets/data/austria/sah/
    - assets/data/slovenia/en/
    - assets/data/slovenia/ru/
    - assets/data/slovenia/sah/
    - assets/data/croatia/en/
    - assets/data/croatia/ru/
    - assets/data/croatia/sah/
    - assets/data/bosnia_and_herzegovina/en/
    - assets/data/bosnia_and_herzegovina/ru/
    - assets/data/bosnia_and_herzegovina/sah/
    - assets/data/albania/en/
    - assets/data/albania/ru/
    - assets/data/albania/sah/
    - assets/data/montenegro/en/
    - assets/data/montenegro/ru/
    - assets/data/montenegro/sah/
    - assets/data/malaysia/en/
    - assets/data/malaysia/ru/
    - assets/data/malaysia/sah/
    - assets/data/singapore/en/
    - assets/data/singapore/ru/
    - assets/data/singapore/sah/
    - assets/data/indonesia/en/
    - assets/data/indonesia/ru/
    - assets/data/indonesia/sah/
    - assets/data/papua_new_guinea/en/
    - assets/data/papua_new_guinea/ru/
    - assets/data/papua_new_guinea/sah/
    - assets/data/india/en/
    - assets/data/india/ru/
    - assets/data/india/sah/
    - assets/data/myanmar/en/
    - assets/data/myanmar/ru/
    - assets/data/myanmar/sah/
    - assets/data/laos/en/
    - assets/data/laos/ru/
    - assets/data/laos/sah/
    - assets/data/thailand/en/
    - assets/data/thailand/ru/
    - assets/data/thailand/sah/
    - assets/data/tunisia/en/
    - assets/data/tunisia/ru/
    - assets/data/tunisia/sah/
    - assets/data/morocco/en/
    - assets/data/morocco/ru/
    - assets/data/morocco/sah/
    - assets/data/libya/en/
    - assets/data/libya/ru/
    - assets/data/libya/sah/
    - assets/data/algeria/en/
    - assets/data/algeria/ru/
    - assets/data/algeria/sah/
    - assets/data/mongolia/en/
    - assets/data/mongolia/ru/
    - assets/data/mongolia/sah/
    - assets/data/azerbaijan/en/
    - assets/data/azerbaijan/ru/
    - assets/data/azerbaijan/sah/
    - assets/data/armenia/en/
    - assets/data/armenia/ru/
    - assets/data/armenia/sah/
    - assets/data/georgia/en/
    - assets/data/georgia/ru/
    - assets/data/georgia/sah/
    - assets/data/australia/en/
    - assets/data/australia/ru/
    - assets/data/australia/sah/
    - assets/data/egypt/en/
    - assets/data/egypt/ru/
    - assets/data/egypt/sah/
    - assets/data/brazil/en/
    - assets/data/brazil/ru/
    - assets/data/brazil/sah/
    - assets/data/uk/en/
    - assets/data/uk/ru/
    - assets/data/uk/sah/
    - assets/data/belarus/en/
    - assets/data/belarus/ru/
    - assets/data/belarus/sah/
    - assets/data/argentina/en/
    - assets/data/argentina/ru/
    - assets/data/argentina/sah/
    - assets/data/bolivia/en/
    - assets/data/bolivia/ru/
    - assets/data/bolivia/sah/
    - assets/data/chile/en/
    - assets/data/chile/ru/
    - assets/data/chile/sah/
    - assets/data/paraguay/en/
    - assets/data/paraguay/ru/
    - assets/data/paraguay/sah/
    - assets/data/peru/en/
    - assets/data/peru/ru/
    - assets/data/peru/sah/
    - assets/data/cuba/en/
    - assets/data/cuba/ru/
    - assets/data/cuba/sah/
    - assets/data/panama/en/
    - assets/data/panama/ru/
    - assets/data/panama/sah/
    - assets/data/ecuador/en/
    - assets/data/ecuador/ru/
    - assets/data/ecuador/sah/
    - assets/data/colombia/en/
    - assets/data/colombia/ru/
    - assets/data/colombia/sah/
    - assets/data/bhutan/en/
    - assets/data/bhutan/ru/
    - assets/data/bhutan/sah/
    - assets/data/philippines/en/
    - assets/data/philippines/ru/
    - assets/data/philippines/sah/
    - assets/data/maldives/en/
    - assets/data/maldives/ru/
    - assets/data/maldives/sah/
    - assets/data/sri_lanka/en/
    - assets/data/sri_lanka/ru/
    - assets/data/sri_lanka/sah/
    - assets/data/el_salvador/en/
    - assets/data/el_salvador/ru/
    - assets/data/el_salvador/sah/
    - assets/data/nicaragua/en/
    - assets/data/nicaragua/ru/
    - assets/data/nicaragua/sah/
    - assets/data/guatemala/en/
    - assets/data/guatemala/ru/
    - assets/data/guatemala/sah/
    - assets/data/haiti/en/
    - assets/data/haiti/ru/
    - assets/data/haiti/sah/
    - assets/data/turkey/en/
    - assets/data/turkey/ru/
    - assets/data/turkey/sah/
    - assets/data/south_africa/en/
    - assets/data/south_africa/ru/
    - assets/data/south_africa/sah/
    - assets/data/italy/en/
    - assets/data/italy/ru/
    - assets/data/italy/sah/
    - assets/data/germany/en/
    - assets/data/germany/ru/
    - assets/data/germany/sah/
    - assets/data/switzerland/en/
    - assets/data/switzerland/ru/
    - assets/data/switzerland/sah/
    - assets/data/spain/en/
    - assets/data/spain/ru/
    - assets/data/spain/sah/
    - assets/data/south_korea/en/
    - assets/data/south_korea/ru/
    - assets/data/south_korea/sah/
    - assets/data/new_zealand/en/
    - assets/data/new_zealand/ru/
    - assets/data/new_zealand/sah/
    - assets/data/kazakhstan/en/
    - assets/data/kazakhstan/ru/
    - assets/data/kazakhstan/sah/
    - assets/data/uzbekistan/en/
    - assets/data/uzbekistan/ru/
    - assets/data/uzbekistan/sah/
    - assets/data/kyrgyzstan/en/
    - assets/data/kyrgyzstan/ru/
    - assets/data/kyrgyzstan/sah/
    - assets/data/tajikistan/en/
    - assets/data/tajikistan/ru/
    - assets/data/tajikistan/sah/

flutter_launcher_icons:
  android: true
  ios: true
  remove_alpha_ios: true
  image_path: "assets/app_icon.png"
  min_sdk_android: 21
  web:
    generate: true
    image_path: "assets/app_icon.png"
    background_color: "#101010"
    theme_color: "#101010"
  windows:
    generate: true
    image_path: "assets/app_icon.png"
    icon_size: 48
  macos:
    generate: true
    image_path: "assets/app_icon.png"
