name: quiz_app
description: Простая игра-викторина на Flutter
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.2.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6
  flutter_svg: ^2.0.10
  url_launcher: ^6.3.1
  shared_preferences: ^2.3.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0
  flutter_launcher_icons: ^0.14.3

flutter:
  uses-material-design: true

  assets:
    - assets/flags/
    - assets/question_images/
    - output/imagegen/world_map_no_labels_8k.png
    - assets/data/russia/en/
    - assets/data/russia/ru/
    - assets/data/russia/sah/
    - assets/data/russia/yakutia/
    - assets/data/russia/yakutia/en/
    - assets/data/russia/yakutia/ru/
    - assets/data/russia/yakutia/sah/
    - assets/data/russia/dagestan/
    - assets/data/russia/dagestan/en/
    - assets/data/russia/dagestan/ru/
    - assets/data/russia/dagestan/sah/
    - assets/data/usa/en/
    - assets/data/usa/ru/
    - assets/data/usa/sah/
    - assets/data/usa/oklahoma/en/
    - assets/data/usa/oklahoma/ru/
    - assets/data/usa/oklahoma/sah/
    - assets/data/usa/texas/en/
    - assets/data/usa/texas/ru/
    - assets/data/usa/texas/sah/
    - assets/data/china/en/
    - assets/data/china/ru/
    - assets/data/china/sah/
    - assets/data/vietnam/en/
    - assets/data/vietnam/ru/
    - assets/data/vietnam/sah/
    - assets/data/japan/en/
    - assets/data/japan/ru/
    - assets/data/japan/sah/
    - assets/data/mexico/en/
    - assets/data/mexico/ru/
    - assets/data/mexico/sah/
    - assets/data/canada/en/
    - assets/data/canada/ru/
    - assets/data/canada/sah/
    - assets/data/poland/en/
    - assets/data/poland/ru/
    - assets/data/poland/sah/
    - assets/data/france/en/
    - assets/data/france/ru/
    - assets/data/france/sah/
    - assets/data/romania/en/
    - assets/data/romania/ru/
    - assets/data/romania/sah/
    - assets/data/bulgaria/en/
    - assets/data/bulgaria/ru/
    - assets/data/bulgaria/sah/
    - assets/data/greece/en/
    - assets/data/greece/ru/
    - assets/data/greece/sah/
    - assets/data/australia/en/
    - assets/data/australia/ru/
    - assets/data/australia/sah/
    - assets/data/egypt/en/
    - assets/data/egypt/ru/
    - assets/data/egypt/sah/
    - assets/data/brazil/en/
    - assets/data/brazil/ru/
    - assets/data/brazil/sah/
    - assets/data/uk/en/
    - assets/data/uk/ru/
    - assets/data/uk/sah/
    - assets/data/belarus/en/
    - assets/data/belarus/ru/
    - assets/data/belarus/sah/
    - assets/data/argentina/en/
    - assets/data/argentina/ru/
    - assets/data/argentina/sah/
    - assets/data/turkey/en/
    - assets/data/turkey/ru/
    - assets/data/turkey/sah/
    - assets/data/south_africa/en/
    - assets/data/south_africa/ru/
    - assets/data/south_africa/sah/
    - assets/data/italy/en/
    - assets/data/italy/ru/
    - assets/data/italy/sah/
    - assets/data/germany/en/
    - assets/data/germany/ru/
    - assets/data/germany/sah/
    - assets/data/switzerland/en/
    - assets/data/switzerland/ru/
    - assets/data/switzerland/sah/
    - assets/data/spain/en/
    - assets/data/spain/ru/
    - assets/data/spain/sah/
    - assets/data/south_korea/en/
    - assets/data/south_korea/ru/
    - assets/data/south_korea/sah/
    - assets/data/new_zealand/en/
    - assets/data/new_zealand/ru/
    - assets/data/new_zealand/sah/
    - assets/data/kazakhstan/en/
    - assets/data/kazakhstan/ru/
    - assets/data/kazakhstan/sah/
    - assets/data/uzbekistan/en/
    - assets/data/uzbekistan/ru/
    - assets/data/uzbekistan/sah/
    - assets/data/kyrgyzstan/en/
    - assets/data/kyrgyzstan/ru/
    - assets/data/kyrgyzstan/sah/
    - assets/data/tajikistan/en/
    - assets/data/tajikistan/ru/
    - assets/data/tajikistan/sah/

flutter_launcher_icons:
  android: true
  ios: true
  remove_alpha_ios: true
  image_path: "assets/app_icon.png"
  min_sdk_android: 21
  web:
    generate: true
    image_path: "assets/app_icon.png"
    background_color: "#101010"
    theme_color: "#101010"
  windows:
    generate: true
    image_path: "assets/app_icon.png"
    icon_size: 48
  macos:
    generate: true
    image_path: "assets/app_icon.png"
